package com.cg.lab4;

class NextAccountNumber {
	public static long autoGeneratedAccountNumber = 11111111110L;
}
public class Account {
	
	private long accNum = NextAccountNumber.autoGeneratedAccountNumber++;
	private double balance;
	private Person accHolder;
	
	public void deposite(double amount) {
		balance += amount;
	}
	public void withdraw(double amount) {
		balance -= amount;
	}
	public long getAccNum() {
		return accNum;
	}
	
	public double getBalance() {
		return balance;
	}
	public void setBalance(double balance) {
		this.balance = balance;
	}
	public Person getAccHolder() {
		return accHolder;
	}
	public void setAccHolder(Person accHolder) {
		this.accHolder = accHolder;
	}
	public Account(double balance, Person accHolder) {
		super();
		this.balance = balance;
		this.accHolder = accHolder;
	}
	@Override
	public String toString() {
		return "Account [accNum=" + accNum + ", balance=" + balance + ", accHolder=" + accHolder + "]";
	}
	
	
}
